### ISSUE TITLE
On Hover theme issue

### ISSUE THREAD

**Issue by DNYLA** [sbondCo/Watcharr#112]
Hard to spot it in the GIF but whenever you hover over an actor card it flashes white for a brief moment and then switches to the correct colour. This issue doesn't happen in light mode so im guessing there is a theming issue where the colour falls back to a default value until it can get the theme?
![PGddvEw](https://github.com/sbondCo/Watcharr/assets/22224922/a437fdf3-3c64-4c18-bde8-f5ec2b2b4ea0)

**Comment by IRHM** [comment]
That makes a lot of sense, could be the theming messing up like you say.

I'll add this to the `v1.15.0` milestone.
