### ISSUE TITLE
Spoiler Settings

### ISSUE THREAD

**Issue by DNYLA** [sbondCo/Watcharr#113]
A spoiler setting which would hide information about a shows episode / season details.  It would be hard to distinguish when or what shows a user would want this to appear on though so to make it better you could also add an extra setting which only adds the spoiler preview when a user has selected that they are currently watching, on hold or dropped a show.

**Comment by IRHM** [comment]
Good idea!

I think when the spoiler setting is toggled on, we should hide the thumbnail (and show only on click to reveal) and the description (when that's added).

@DNYLA  I think showing the name of episode and rating is fine?

**Comment by DNYLA** [comment]
> Good idea!
> 
> I think when the spoiler setting is toggled on, we should hide the thumbnail (and show only on click to reveal) and the description (when that's added).
> 
> @DNYLA I think showing the name of episode and rating is fine?

Yea actually on click to reveal is a good idea and showing ratings is fine but im not sure if all users would want to see episode names if they have the spoiler mode enabled.

**Comment by IRHM** [comment]
> > Good idea!
> > I think when the spoiler setting is toggled on, we should hide the thumbnail (and show only on click to reveal) and the description (when that's added).
> > @DNYLA I think showing the name of episode and rating is fine?
> 
> Yea actually on click to reveal is a good idea and showing ratings is fine but im not sure if all users would want to see episode names if they have the spoiler mode enabled.

Sounds good, thanks for the input. Guess we can do the same sort of click to reveal with episode names too (maybe down the line if people want it, more settings to fully customize what is shown would be good).
