### ISSUE TITLE
Can't register/login

### ISSUE THREAD

**Issue by MathieuMoalic** [sbondCo/Watcharr#143]
Hi, I can't seem to be able to setup watcharr correctly and I can't login/register. Pressing the login/register button on the WebUI does nothing except print "WATCHARR v1.18." in the logs with **DEBUG=true**.
I use podman on fedora server and I run watcharr with the following command:
```txt
podman network create --ignore watcharr-proxy
podman run -d --replace --tz local --pull newer \
    --name watcharr \
    --network watcharr-proxy \
    -v ./watcharr/.env:/.env:z \
    -v ./watcharr/data:/data:z \
    ghcr.io/sbondco/watcharr:v1.18.0
```

The browser console log show:
```
/api/auth/register:1     Failed to load resource: the server responded with a status of 404 ()
/api/auth/register:1     Failed to load resource: the server responded with a status of 404 ()
/api/auth/register:1     Failed to load resource: the server responded with a status of 404 ()
/api/auth/register:1     Failed to load resource: the server responded with a status of 404 ()
/api/auth/:1     Failed to load resource: the server responded with a status of 404 ()
/api/auth/:1     Failed to load resource: the server responded with a status of 404 ()
/api/auth/:1     Failed to lo
```

I suspected there might be permission issues with the database so I `chmod 777 -R ./data` and I got the following browser errors instead:
```
api.10c2844a.js:3     POST https://watcharr.matmoa.xyz/api/auth/ 404
(anonymous) @ api.10c2844a.js:3
xhr @ api.10c2844a.js:3
ye @ api.10c2844a.js:3
request @ api.10c2844a.js:3
(anonymous) @ api.10c2844a.js:3
(anonymous) @ api.10c2844a.js:1
a @ 15.f6d3b3d5.js:1
(anonymous) @ index.90c64be0.js:1
api.10c2844a.js:3     POST https://watcharr.matmoa.xyz/api/auth/register 404
(anonymous) @ api.10c2844a.js:3
xhr @ api.10c2844a.js:3
ye @ api.10c2844a.js:3
request @ api.10c2844a.js:3
(anonymous) @ api.10c2844a.js:3
(anonymous) @ api.10c2844a.js:1
a @ 15.f6d3b3d5.js:1
(anonymous) @ index.90c64be0.js:1
```
Any thoughts ? :)

P.S. everywhere here the port 3080 is mentionned but the http server definetly serves on port 3000, how come ?

**Comment by MathieuMoalic** [comment]
Oops, my mistake, I got baited by the `Listening on 0.0.0.0:3000` and proxied this port instead of 3080. 
port 3000 seems to server a broken version of the frontend somehow.

**Comment by IRHM** [comment]
> Oops, my mistake, I got baited by the `Listening on 0.0.0.0:3000` and proxied this port instead of 3080. port 3000 seems to server a broken version of the frontend somehow.

Hey, no worries. Glad you were able to get it fixed!

When running Watcharr, it also runs the frontend on port 3000 and proxies requests to it to serve the content. That may explain the buggy frontend.

I can see how that log is confusing though, I'm not sure If I log it or a library logs it, but I'll have a look and see if I can change it.

Thanks!

Edit: Turns out the log is generated by the frontend build, not sure if there's an easy way to remove that.
