### ISSUE TITLE
Track video games

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#167]
Let user search for and track video games with the same experience flow as movies/shows.

This looks like a decent (only one i found) api we can use for searching games: https://api-docs.igdb.com

We would also have to consider how search should work, many people wouldn't want video games to show up in results. We could have a dropdown thing integrated into the searchbar to allow users to pick what content types to search for (tv and movies or games, or both [default to tv and movies]).

And of course new video game filters for `watched list`.

Haven't looked into it yet, hopefully we can get the data to look like how shows are. Not sure if we could store it in the same `content` table or if it'd be better to separate it out.

**Comment by mordquist** [comment]
> We could have a dropdown thing integrated into the searchbar to allow users to pick what content types to search for...

Perhaps reuse the list filter to only search for types of media displayed? For example if you are displaying only movies, only search for movies.

**Comment by IRHM** [comment]
@mordquist that is a genius idea and much less complicated than the dropdown thing I thought up. Thank you, I'll definitely keep that in mind.
