### ISSUE TITLE
Nav: Make searchbar take up 100% width when focused on mobile

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#168]
Make searchbar take up 100%  width when focused on mobile.

Nav can get a bit cramped on mobile, this should help provide a better experience when searching.

**Comment by simonbcn** [comment]
I think one solution would be to allow installation of this app as a PWA on mobile/tablet. I don't know if this is easy to do but I think it would make it look much better on mobile.

**Comment by IRHM** [comment]
> I think one solution would be to allow installation of this app as a PWA on mobile/tablet. I don't know if this is easy to do but I think it would make it look much better on mobile.

Unfortunately, I don't have any experience with PWAs, but it is definitely a welcome feature that I'll look into. I've created a separate ticket to track it: #225
