### ISSUE TITLE
Unable to compile from source

### ISSUE THREAD

**Issue by simonbcn** [sbondCo/Watcharr#181]
```
CachyOS Linux (Arch Linux)
```

I have followed [this guide to compile from **git** source](https://watcharr.app/docs/installation/from-source).

All it's ok but the last step fails:
```
$ GOOS=linux go build -o ./watcharr
activity.go:5:2: package log/slog is not in GOROOT (/usr/src/log/slog)
```

**Comment by IRHM** [comment]
Hi @simonbcn, thanks for reaching out!

slog is new in go 1.21 (i believe its that version). Is it possible you have a slighly older version installed? You can check with: `go version`

**Comment by simonbcn** [comment]
Fixed, the problem was that I had installed `gcc-go` instead of `go`.
