### ISSUE TITLE
Better User Pages

### ISSUE THREAD

**Issue by DNYLA** [sbondCo/Watcharr#192]
Some of these features are probably in the idea book but I have a list of features that would improve the user experience.

- [x] #234 
- [x] #238
- [ ] #235
- [x] #237
- [x] #236

**Comment by IRHM** [comment]
Hi @DNYLA, thank you for the ideas, these will definitely improve the user experience and add a lot of nice functionality to the app.

**Comment by IRHM** [comment]
Will continue to track the outstanding tasks in their own tickets.
