### ISSUE TITLE
SeasonsList: Hide Spoiler setting should also hide the episode rating

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#217]
SeasonsList: Hide Spoiler profile setting should also hide the episode rating.

The rating of an episode could spoil if its a good or bad episode. Watching a series and seeing the next episode has a 0.0002 stars out of 10 kinda spoils that it is trash.

We could add a separate button to only unhide the rating for people who dont want to waste time on badly rated episodes, without revealing thumbnail.

**Comment by ishaanparlikar** [comment]
Can I pick it up?

**Comment by IRHM** [comment]
> Can I pick it up?

Hey @ishaanparlikar, you certainly can! Thank you!

Let me know if I can help with anything.

**Comment by ishaanparlikar** [comment]
Hi @IRHM  Thanks,
Can you let me know how to setup the backend? I can't create a user? Or should I just bypass the flow?

**Comment by IRHM** [comment]
> Hi @IRHM Thanks, Can you let me know how to setup the backend? I can't create a user? Or should I just bypass the flow?

Were you able to get it working? Once you run the backend, it should setup everything for you, then navigating to the frontend in your browser will allow you to make a user.

This should download the packages for you:
```
cd server && go mod download
```

Then go back to root folder and run the server:
```
cd ../ && npm run server
```

Hopefully this gets it setup for you, any troubles with that let me know.

**Comment by ishaanparlikar** [comment]
Hey @IRHM 

does this look okay? or position of second button needs to be updated?

Current:
![image](https://github.com/sbondCo/Watcharr/assets/43013132/4fcbbb18-a227-4620-94f1-a487d6b9cf99)

Width Adjusted:
![image](https://github.com/sbondCo/Watcharr/assets/43013132/d960ec87-38d1-41bf-a166-dbc33801eed3)

**Comment by IRHM** [comment]
@ishaanparlikar that's weird, there should be a ratings button besides that one.

**Comment by ishaanparlikar** [comment]
@IRHM  Oh you mean it should hide episode rating not the whole show rating? Also, if user clicks on it then it should unhide it again?

**Comment by IRHM** [comment]
> @IRHM Oh you mean it should hide episode rating not the whole show rating? Also, if user clicks on it then it should unhide it again?

Ah, yes sorry. I thought that was a bug happeneing to you.

Just hiding episode ratings from the tv show page should be good, when the user has the spoiler setting enabled in their profile.

Adding it to reveal when the episode is clicked like the other details should be good.

Should find this in the SeasonsList component.

**Comment by IRHM** [comment]
Just went to get this screenshot, it's on this section, on the tv show page at the bottom you should see it:

![image](https://github.com/sbondCo/Watcharr/assets/37304121/99af08a4-ed94-40fe-944e-ecf26afcd711)
