### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#225]
Look into making Watcharr a PWA.

**Comment by ishaanparlikar** [comment]
Hey @IRHM 

I can try working on this. Would be fun to explore.

**Comment by IRHM** [comment]
> Hey @IRHM
> 
> I can try working on this. Would be fun to explore.

Hey @ishaanparlikar, that would be great, I'll assign you.

**Comment by ishaanparlikar** [comment]
Hi @IRHM 
How do I get APIs to work in final bundled app or when we build the project? 
I get this error when running in production mode.
![image](https://github.com/sbondCo/Watcharr/assets/43013132/6b61661c-2e60-4b56-bf02-66a55d0e064c)

**Comment by IRHM** [comment]
Hey @ishaanparlikar, sorry for the late response.
I wrote a guide on building from source for production, hopefully it helps: [https://watcharr.app/docs/installation/from-source](https://watcharr.app/docs/installation/from-source)

Let me know if that helps, if not let me know, I can help debug the issue further with you.

As a side note: if you have docker compose you can build a production image and run it easily by running this in the project root folder (this is how I test prod locally, doing it manually can be a bit annoying):
```
docker compose -f docker-compose.dev.yml up --build
```

**Comment by ishaanparlikar** [comment]
Hey @IRHM 
Can you check? That CSS for blurring from earlier PR got into this too. I hope its not a problem. Please have a look into PWA and let me know.
Thanks

**Comment by IRHM** [comment]
Hi @ishaanparlikar, I had a look, it shouldn't be an issue, I can fix it if any merge conflicts happen.

Added a review to the PR, just realised by default it won't work in dev environment, going to test it again with a build.

**Comment by ishaanparlikar** [comment]
Hi @IRHM 
Yes you will have to build it first. Then it will work

**Comment by IRHM** [comment]
@ishaanparlikar Also found out to install we are required to have https. I don't have time to setup something locally, if you are able to check the PR review and see if those lines can be removed (if you can't at the moment, let me know if I can remove them), I'll merge and test in the actual `dev` environment.

**Comment by ishaanparlikar** [comment]
@IRHM I have tried on my system, i was able to do it without https. Can you show what error you are getting?

**Comment by IRHM** [comment]
> @IRHM I have tried on my system, i was able to do it without https. Can you show what error you are getting?

Oh that's weird. I don't get any errors, I just don't get the `Install` app button in my browser. I found a stackoverflow comment that refers to this MDN page, stating https is required for their example. Thought it may just be a requirement in general?

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Installable_PWAs#requirements

https://stackoverflow.com/questions/58985103/progressive-web-app-not-showing-install-button-in-browser-bar (first comment on post)

**Comment by IRHM** [comment]
@ishaanparlikar Oh that might be wrong, I just found a page saying localhost is considered secure: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#secure_context

![image](https://github.com/sbondCo/Watcharr/assets/37304121/4238f650-1991-422c-bfa7-2a6dd209547d)

Not sure what is happening, I'm guessing something weird with my setup

**Comment by IRHM** [comment]
@ishaanparlikar Yup sorry for the spam. It worked on desktop chromium, firefox esr and librewolf don't get the install button, I'm guessing that's a problem with them though.

I'll merge the PR whenever you get a chance to look at the comments I added to it, then I'll test on `dev`.

**Comment by ishaanparlikar** [comment]
@IRHM 
Yes firefox and safari dont have pwa support on desktop


![image](https://github.com/sbondCo/Watcharr/assets/43013132/64a25bcd-aecd-492e-a2a7-e53cf57fb0cd)

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Guides/Making_PWAs_installable#browser_support

**Comment by IRHM** [comment]
@ishaanparlikar Ah that's good to know! Had no idea, I assumed of any browser, FireFox would support it on desktop.
