### ISSUE TITLE
Integrate impler.io for Importing WatchList

### ISSUE THREAD

**Issue by chavda-bhavik** [sbondCo/Watcharr#226]
Hi, Bhavik at this side from https://github.com/implerhq/impler.io, 

Found about `Watcharr` from GitHub and used a demo. We can give users a better experience in importing WatchList from TMDb. At the moment it's hard to cover edge cases in import like,
- File is empty
- User tries to import incorrect file
- Header not matching
etc...

Instead, we can integrate `Impler's` data import widget and handle importing WatchList data by it. The imported data will be received via webhook.

Attaching the video link of how import will look like, https://vimeo.com/869770674/22169e8fdc

I'm willing to work on it.

**Comment by IRHM** [comment]
Hi @chavda-bhavik, impler looks super cool. Unfortunately, with Watcharr being primarily a selfhosted app, I think using impler would complicate the process of users setting up Watcharr locally.

From the docs it looks like if someone setup a Watcharr instance locally, they would need to go through impler setup too.

**Comment by chavda-bhavik** [comment]
Thanks @IRHM.

If we talk about users setting up Watcharr locally, they can just create an Import over Impler (takes 2 minutes) and provide their keys in env.

And Impler is available for free on https://web.impler.io and users don't have to set it up themselves.

To make this process easier, I will be happy to write step-by-step instructions in ReadMe for getting Impler keys from Impler.

Will that work?

**Comment by IRHM** [comment]
@chavda-bhavik I'm leaning towards no on this, I'm not sure it's worth the extra hassle for end users.

Maybe if the widget could be used as a package fully locally (and fully customizable to fit the site styling) I could see that being a big benefit, but I'm not a big fan of the extra setup required or relying on the free hosted version being available down the line.

Thank you for sharing impler, I'll leave this issue up for now so I can think about it or see if anyone else has any opinions.

**Comment by IRHM** [comment]
Just going to close this now, been open for a while. If anyone has any futher suggestions around this, please feel free to open a new issue.

For now, I don't think we will be integrating Impler.

Thanks again!
