### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#279]
New button in profile settings to allow the user to change their password. Probably should open a new modal that allows the user to input their `current password` and a `new password`.

**Comment by iamericfletcher** [comment]
I'm happy to take this task if you're okay with assigning it to me!

I've got a design question regarding changing the `width: min-content` to `width: 100%` for buttons within `div.row.btns`. To me it seems a tad bit more balanced with `width: 100%`.

so: 

```
div {
      &.row {
        display: flex;
        flex-flow: row;
        gap: 10px;
        align-items: center;

        &.btns button {
          width: min-content;
        }
      }
    }
```
to:
```

    div {
      &.row {
        display: flex;
        flex-flow: row;
        gap: 10px;
        align-items: center;

        &.btns button {
          width: 100%;
        }
      }
    }

```
**width: min-content**
![image](https://github.com/sbondCo/Watcharr/assets/64165327/efadf003-7874-4e9c-b52d-0707a5711a7e)

**width: 100%**
![image](https://github.com/sbondCo/Watcharr/assets/64165327/aca68c67-fa94-48e9-b033-dcc6d974a331)

Also, it seems to be in line with the text inputs and buttons in server settings. 

![image](https://github.com/sbondCo/Watcharr/assets/64165327/f3e09322-d7bd-489d-bf34-7d0306a43970)

**Comment by IRHM** [comment]
Thank you @iamericfletcher, I've assigned you.

What do you think about something like this (`width: max-content;`)?

![image](https://github.com/sbondCo/Watcharr/assets/37304121/7c050924-0317-4fdd-8178-8dfc1fd57869)

**Comment by iamericfletcher** [comment]
Yes - I love your version. I'll use it and begin on the more technical implementation tomorrow :)

**Comment by IRHM** [comment]
Sounds great, if you have any questions feel free to let me know!

**Comment by iamericfletcher** [comment]
Thanks :) This project is freaking awesome for someone like me (on the newer side of things with an intense passion for technology and programming). I'm in a non-technical position at the day-job, but really am taking to programming as a hobby. You are incredibly talented as shown in the detail and care put into this code base! The way it's structured and all the different techniques you use is a gold mine, so thanks so much! Look forward to making progress on this issue.

**Comment by IRHM** [comment]
You make me blush, thank you! Have fun!

**Comment by iamericfletcher** [comment]
Progress being made!

![image](https://github.com/sbondCo/Watcharr/assets/64165327/c4d5c6a5-873e-405e-860c-916bfafcbf47)

![image](https://github.com/sbondCo/Watcharr/assets/64165327/1f5c6ff2-a16b-4be1-803b-f7d968f6f8aa)

![image](https://github.com/sbondCo/Watcharr/assets/64165327/6ff834ba-8ab4-4514-8595-dd7798c8d0f1)

**Comment by IRHM** [comment]
@iamericfletcher That is looking great!

**Comment by iamericfletcher** [comment]
Thank you :) Will remove the excess console.logs -- now trying to implement the server logic :) Thinking of adding it to the authentication required `addUserRoutes` group like `/user/change_password`. 

Hopefully will have something for your review soon.
