### ISSUE TITLE
'Detail' view

### ISSUE THREAD

**Issue by Contrillion-2** [sbondCo/Watcharr#296]
Feature idea/suggestion. It would be great to be able to switch the watched list to something like a 'detail view', giving access to some additional metadata on the one page. 

Would be particularly useful for shows/series where users are more likely to have left something in 'watching' state and are deciding what to pick up again (and where they are up to in that show), without needing to click into each item to see more detail about its status.

The ability to view and sort by details such as:
- Date added
- Date last modified
- Completion status (for shows- what was the latest season marked finished/watching? And eventually which episode - somewhat related to issue #42 )

**Comment by IRHM** [comment]
Hi @Contrillion-2, thank you for the suggestions!

The ideas are great, when I have some time I will definitely look into this.

Would you prefer a table view with extra detail or the same grid but adding the extra metadata below posters?

Sorting/filtering should be implemented (button to right of nav) for those currently, is there something missing with how it is now?

**Comment by Contrillion-2** [comment]
Probably the critical part imo would be the ability to see the progress of in-progress shows, so if it were visible in the grid view that would accomplish it. The table view might be a separate issue, now that I think of it.

To illustrate, if I want to find where I'm up to in a show currently, I could filter the list by 'watching' and 'held', but I would then need to go into a show in the list, and click through each season one by one until I found the one I last marked completed/watching (to be fair it is usually at the top of the activity log!). But it would be good to see this in less clicks with something like "Watching Season 8" (and eventually "last watched S08E05") at-a-glance in the main watched list view. 

And yes, to clarify, sorting and filtering is fine and works quite well now, I guess that comment was more directed at a table view scenario.

**Comment by IRHM** [comment]
@Contrillion-2 Got a simple **design** working for a detailed poster, is this along the lines of what you envisioned?

![image](https://github.com/sbondCo/Watcharr/assets/37304121/f7313ffa-e341-44b1-87ec-cc2a6b840ad6)

_any feedback is appeciate . me think look ugly but also nice_

**Comment by Contrillion-2** [comment]
Appreciate you taking the time to do a mockup! Yes, that looks good. Maybe the dates can go, for the poster view, leaving just the 'Season 2' and rating/status icons. Otherwise may be a bit too cluttered.

**Comment by IRHM** [comment]
I agree with you calling the mockup ugly and disappointing. Anyways, I revised the design and made the displayed fields configurable with a new menu.

![image](https://github.com/sbondCo/Watcharr/assets/37304121/0a20db5d-b7d8-435b-b769-24c5751f0e2a) ![image](https://github.com/sbondCo/Watcharr/assets/37304121/cc90d08d-c915-4172-baf8-5625e196b9b9)

I'll look to finish it tonight or tomorrow and release it for you to try.

**Comment by IRHM** [comment]
Sorry that took a while to get done @Contrillion-2, released in [v1.31](https://github.com/sbondCo/Watcharr/releases/tag/v1.31.0). Feel free to open another issue if you have any other problems.

Thanks again!
