### ISSUE TITLE
Adding image for arm/raspberry

### ISSUE THREAD

**Issue by schmurian** [sbondCo/Watcharr#309]
I would like to run watcharr locally on a raspberry pi but when I try to run the docker compose, it returns this message:

>  ! watcharr The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

I tried to build it from source but this returned another Error when starting the server like mentioned in the documetation:

> time=2024-01-09T08:39:06.629+01:00 level=INFO msg="UI ERR @ command wait: exit status 1"

**Comment by IRHM** [comment]
Hi @schmurian, luckily I have a pi I can test this on. When I'm free tonight, I'll see if I can get it working.

I'll release a new version and let you know If I can get it running.

Thanks for your interest in the project!

**Comment by schmurian** [comment]
Oh that would be fantastic! Thank you for looking into it.

**Comment by IRHM** [comment]
@schmurian `v1.31.1` is building now and should be published in ~10m for you to try out.

thanks again for taking the time to create this issue!

**Comment by schmurian** [comment]
Wow that was super-fast! Thank you so much. Looking forward to have this finally installed.
