### ISSUE TITLE
Importing: Support syncing Watch History and Ratings from Plex Login

### ISSUE THREAD

**Issue by stephaje** [sbondCo/Watcharr#359]
If a user is signed in with a Plex account, they should have the option to sync their watch history and/or their media ratings. This mildly overlaps with https://github.com/sbondCo/Watcharr/issues/82.

**Comment by IRHM** [comment]
Hey @stephaje, once #358 and #82 are completed I will definitely come back to this.

Hopefully the code will be mostly reusable for syncing so after #82 this should be much simpler.

**Comment by stephaje** [comment]
@IRHM I can start taking a look at this, unless you'd prefer to.

**Comment by IRHM** [comment]
> @IRHM I can start taking a look at this, unless you'd prefer to.

Hey, feel free, I'll assign you. Thanks!

Should be able to use `jellyfin_sync.go` as a rough guide for getting it working for plex. Sorry in advance for the ungodly size of the main function in there, I didn't think it was worth (the time) separating out something like that.
