### ISSUE TITLE
Authorization: Allow for Disabling New Account Creation

### ISSUE THREAD

**Issue by stephaje** [sbondCo/Watcharr#361]
It should be possible to toggle if new accounts are allowed to be created. This removes the ability malicious users to spam the system with spam data.

**Comment by IRHM** [comment]
Hi @stephaje, thanks for making the issue. This is actually already available with this setting:

![image](https://github.com/sbondCo/Watcharr/assets/37304121/dea533b8-2af8-4af9-9524-f7880c606b28)

When disabled, the signup logic is disabled and the 'Not a user?' button is hidden on login page.

**Comment by stephaje** [comment]
Yeah, I just noticed as I built from source and got logged in with an admin account. Sorry!
