### ISSUE TITLE
Watching a TV Show or a Movie again

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#381]
Some kind of a "watch history" would really help in situations when I watch a movie or a TV show again. I should ideally be able to track or have the ability to document rewatching of a movie or a TV show.

This may be done by adding a "watching again" button and then tracking it in the "activity" section.

Do consider a way to implement a variant of this.

Thank you for creating Watcharr. I love it!

**Comment by n00b12345** [comment]
I guess this can already be achieved by changing the status back to watching or finished again. It will be reflected in the Activity section.

**Comment by IRHM** [comment]
Thanks for trying out Watcharr @n00b12345! Hopefully the solution you found fits your needs, there's also a planned feature #333 which will add to this.
