### ISSUE TITLE
Reduce size of images on the mobile interface

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#385]
This is what the UI looks like on a 6.5 inch mobile device *in portrait mode*. As you can tell, there's a lot of free space on both sides of the images, which requires a lot of scrolling.

![Screenshot_2024-03-02-13-20-02-18_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/sbondCo/Watcharr/assets/17707852/f71bf5ec-0601-4881-b8c9-c91352f27b27)

Things look a lot nicer in landscape mode:

![IMG_20240302_133432.jpg](https://github.com/sbondCo/Watcharr/assets/17707852/9f63bb25-ee6b-438d-879d-56a4b1015b40)

Making the UI a little more dense by reducing the size of the images, would probably make it look a lot more sleek.

**Comment by IRHM** [comment]
Hey @n00b12345, you're right that is a bad experience. I guess making it look good on my phone doesn't mean it will on all phones.

I'll have to see if there's a way I can dynamically scale the posters so we can fit at least two on one row.

I've also been meaning to get to the search bar on mobile (may as well get it done with this task), we have too many icons up there now! I think moving them under the search bar when it gets cramped should be a good solution to this.

Thanks for all the feedback, I appreciate it!
