### ISSUE TITLE
Ability to change date of addition for movies and shows

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#386]
A user who is new to Watcharr is likely to have a long watch history going back beyond the date of installation/deployment.

So, the ability to change the date of the addition or the ability to see the date on which the movie was seen would be nice.

This may not seem like a big deal right now. But, if a feature like yearly stats (similar to Spotify's year-end stats) were to be implemented at some point in the future, the date of addition/viewing might come in handy.

Eg. I know when I saw Avatar 2 in 2022. I should be able to add that to Watcharr in a way which meaningfully reflects the date of viewing.

**Comment by IRHM** [comment]
Hi @n00b12345, we have a feature in the `dev` branch right now that allows you to edit your activity (#61). This would let you change the date on which the Watched activity displays.

Should be released soon. Would that solve this problem for you?

**Comment by n00b12345** [comment]
> Hi @n00b12345, we have a feature in the `dev` branch right now that allows you to edit your activity (#61). This would let you change the date on which the Watched activity displays.
> 
> Should be released soon. Would that solve this problem for you?

It would! Thank you.
