### ISSUE TITLE
Signups get re-enabled after container is recreated/restarted

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#388]
Signups, once disabled from the settings, get re-enabled every time the Docker container is restarted. Ideally, this should be remembered through the application settings.

**Comment by IRHM** [comment]
Hi @n00b12345, this should be getting saved in your `watcharr.json` config.

Sounds like you have discovered a bug, where the setting isn't used at startup (I think).

I'll definitely have a look at this for you soon.

**Comment by IRHM** [comment]
Thanks again for reporting this, will release the fix soon.
