### ISSUE TITLE
Add "restart: unless-stopped" to docker compose file in documentation

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#390]
I think adding `restart: unless-stopped` to the docker-compose file documentation might remove a bit of hassle for users, especially those who may not necessarily be technically sound with docker.

Do consider adding it to the documentation.

**Comment by IRHM** [comment]
Hey @n00b12345, thanks for the suggestion, that makes a lot of sense.

I think originally I tried to keep the example as slim as possible, but adding that to it would definitely help make it a more complete starting (and finishing) point.

Note for self: probably want to update this file too: https://github.com/sbondCo/Watcharr/blob/dev/docker-compose.yml
