### ISSUE TITLE
Registering is disabled in setup admin user panel

### ISSUE THREAD

**Issue by priyajit4u** [sbondCo/Watcharr#400]
I have installed watcharr via docker compose and on first run page is opening for setting up a admin user. When I am done selecting admin user and password and press the set up button it is saying registering is disabled
![Setup Watcharr](https://github.com/sbondCo/Watcharr/assets/134056924/28fbe3a1-59fc-4cb7-bb49-d64c812bf28c)
<img width="768" alt="Setup Watcharr jpeg" src="https://github.com/sbondCo/Watcharr/assets/134056924/03ffb507-526b-4cd3-a7ef-a0cc9462194c">

**Comment by IRHM** [comment]
Hey, sorry about that. Will fix asap.

Thanks for reporting it!

P.S. If you manually edit your `watcharr.json` config, you should be able to set `SINGUP_ENABLED` to true. The current version has a bug where it is defaulting to false. After updating to fixed version, you can do that, or delete your config to generate a new one.

**Comment by IRHM** [comment]
Hey @priyajit4u, `v1.35.2` is building, should be done in about 5 minutes.

I'll leave the issue open for now, if you could test it again with the new version after deleting your `watcharr.json` file that would be a big help in ensuring this has been properly fixed.

Thanks again, hopefully it works for you!

**Comment by priyajit4u** [comment]
Yes the update fixed the issue completely..thanks ..you can close this ticket now

**Comment by IRHM** [comment]
Thats great to hear! Thank you for trying it out!
