### ISSUE TITLE
[Feature request] Users management and follow

### ISSUE THREAD

**Issue by edersong** [sbondCo/Watcharr#411]
I would suggest a way to manage users checking who was signed up and also a way to find users and follow their updates.

**Comment by IRHM** [comment]
Hi @edersong, thanks for the suggestion!

That is a cool feature idea. We could definitely create a table in server settings to make it possible to manage users.

You can currently find users by searching their username, you should see them above the content posters. If you click into their profile, you can see their list and follow them too (currently following just adds the user to the followed users navigation menu button).

**Comment by Gandalf-the-Blue** [comment]
Can I also add demarcation of admin and member accounts, so that there can be a feature to approve/reject requests (Sonarr/Radarr) by admin?
