### ISSUE TITLE
Allow rating of individial episodes

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#42]
User should be able to rate episodes under a tv show.

Also add watched/not watched or maybe assume watched if rated?

**Comment by christ4k** [comment]
For series is a must to be able to add watched state for every episode.

**Comment by IRHM** [comment]
> For series is a must to be able to add watched state for every episode.

Thanks for commenting @christ4k, this is high on the priority list, I will get it done soon.

**Comment by IRHM** [comment]
@christ4k Sorry this took so long, should be a release soon after I test on beta.watcharr.app.

If you have any feedback after trying it out, please feel free to open a new issue.
