### ISSUE TITLE
No manifest for raspberry pi4

### ISSUE THREAD

**Issue by pecbeck** [sbondCo/Watcharr#422]
Unable to run on pi4, no manifest by default . UName shows aarch64, however if I use platform aarch64 in compose.yaml, pulls and runs but exits code 156. New to docker, any help appreciated

**Comment by IRHM** [comment]
Hey @pecbeck, I just replied in the Matrix chat. Figured I would post here for completeness incase anyone else has troubles.

> [I] Just tried with the example docker-compose.yml in the project files [on my pi], it seems to be working for me.
>
> Ran uname, also says aarch64 for me, but it should be the arm64 build.
>
> Are you trying with the example yml file?

If you try giving it the platform `arm64` (or I think `arm64v8` if i needs specifics), it might work.

May be worth posting your compose yml file if the above doesn't work, I can try running that directly to see If I get the same problem.

**Comment by pecbeck** [comment]
Still exits after attaching, 
cat compose.yaml
version: "3"
services:
  watcharr:
    image: ghcr.io/sbondco/watcharr:latest
    container_name: watcharr
    platform: arm64
    ports:
      - 3080:3080
    volumes:
      - ./data:/data
    restart: unless-stopped

If I remove platform, says no manifest

 watcharr The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested 0.0s
Attaching to watcharr
watcharr exited with code 0

i@pi4:/opt/stacks/watcharr $ cat /proc/version
Linux version 6.1.21-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023
pi@pi4:/opt/stacks/watcharr $ uname -mrs
Linux 6.1.21-v8+ aarch64

**Comment by pecbeck** [comment]
BTW docker hello world works ok

**Comment by IRHM** [comment]
@pecbeck

Very weird, my pi gets an identical output from /proc/version and uname, but that compose file works for me.

Might be one of those problems where clearing all your existing local watcharr docker images and containers, then restarting your pi might fix it?

With it stopped, `docker container prune` and `docker image prune` should clear it out for you to try again.

Confirm the container is fully gone: `docker ps -a`
Confirm the images are gone: `docker image ls`

If they are still present you may need to remove them manually with the container/image id (`docker container rm <id>` / `docker image rm <id>`)

**Comment by pecbeck** [comment]
Sure is odd, I already pruned and it pulled latest from git, I've tried everything,  including reinstalling docker, deleting images and directories.  Not sure where to go now
Thanks for helping 
I'll give it one more try using your suggestions

**Comment by IRHM** [comment]
@pecbeck Yep sorry I'm not much help, if it doesn't work, have you tried building yourself with the `docker-compose.dev.yml`? If building yourself works, maybe I need to be building for linux/arm/v8 specifically instead of just arm64.

`docker compose -f docker-compose.dev.yml up --build` in the project root should build.

**Comment by pecbeck** [comment]
Now I'm really confused. Deleted as per your note then this

pi@pi4:/opt/stacks/watcharr $ docker compose up
 [+] Running 9/9
 ✔ watcharr 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                      13.7s    ✔ bca4290a9639 Already exists                                                             0.0s    ✔ 93210f2a4253 Already exists                                                             0.0s    ✔ 2ef1c9a74cd8 Already exists                                                             0.0s    ✔ e8bb1a28a290 Already exists                                                             0.0s    ✔ 2463f8b403fc Already exists                                                             0.0s    ✔ 8d3b531cec55 Already exists                                                             0.0s    ✔ 49167eda3e0a Already exists                                                             0.0s    ✔ 878b58e92e7f Already exists                                                             0.0s  [+] Running 1/1
 ✔ Container watcharr  Recreated                                                             1.3s Attaching to watcharr
watcharr exited with code 0

Like I said,  new to docker

**Comment by IRHM** [comment]
@pecbeck Were they gone from `docker image ls` after deleting? Haven't seen that before, maybe removing them again and restarting could fully clear them?

**Comment by pecbeck** [comment]
OK, killed everything again, back to where I started, seems to be constantly restarting, code 159. I'm stuck

4:/opt/stacks/watcharr $ !1765
docker container ls --all
CONTAINER ID   IMAGE                             COMMAND                  CREATED              STATUS                            PORTS     NAMES
3b31f4972117   ghcr.io/sbondco/watcharr:latest   "docker-entrypoint.s…"   About a minute ago   Restarting (159) 42 seconds ago             watcharr

**Comment by IRHM** [comment]
@pecbeck That's not good. Do you think you could post the output from `docker version`?

I'm guessing not since it exits straight away, but does watcharr logs anything to the data folder?

**Comment by pecbeck** [comment]
I'll try build as you suggest,  but unsure about source, how do I pull it from git
Sorry, bit new to this

**Comment by IRHM** [comment]
No problem @pecbeck, if you `git clone https://github.com/sbondCo/Watcharr.git`, the `docker-compose.dev.yml` file should be in the root folder.

**Comment by pecbeck** [comment]
docker version
Client: Docker Engine - Community
 Version:           25.0.4
 API version:       1.44
 Go version:        go1.21.8
 Git commit:        1a576c5
 Built:             Wed Mar  6 16:32:23 2024
 OS/Arch:           linux/arm
 Context:           default
Server: Docker Engine - Community
 Engine:
  Version:          25.0.4
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       061aa95
  Built:            Wed Mar  6 16:32:23 2024
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by IRHM** [comment]
@pecbeck Thanks for the output.

I was looking at this post online: https://forums.balena.io/t/raspberry-pi-4-64-bit-with-balena-base-images-exitcode-159/63953/6

It looks like you might be running a 32-bit version of docker instead of 64.

My docker version output does indeed say `OS/Arch: linux/arm64`, so that might be the problem.

How did you install docker?

**Comment by pecbeck** [comment]
Build failed, would post log but can't find /root/.npm. here's a screen scrape

79.87 npm ERR!
79.87 npm ERR! Error: Your current platform "linux" and architecture "arm" combination is not yet
supported by the native Rollup build. Please use the WASM build "@rollup/wasm-node" instead.
79.87 npm ERR!
79.87 npm ERR! The following platform-architecture combinations are supported:
79.88 npm ERR! android-arm
79.88 npm ERR! android-arm64
79.88 npm ERR! darwin-arm64
79.88 npm ERR! darwin-x64
79.88 npm ERR! linux-arm
79.88 npm ERR! linux-arm64
79.88 npm ERR! linux-arm64 (musl)
79.88 npm ERR! linux-riscv64
79.88 npm ERR! linux-x64
79.88 npm ERR! linux-x64 (musl)
79.88 npm ERR! win32-arm64
79.89 npm ERR! win32-ia32
79.89 npm ERR! win32-x64
79.89 npm ERR!
79.89 npm ERR! If this is important to you, please consider supporting Rollup to make a native build for your platform and architecture available.
79.89 npm ERR!     at Object.<anonymous> (/app/node_modules/rollup/dist/native.js:38:8)
79.89 npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1376:14)
79.89 npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
79.89 npm ERR!     at Module.load (node:internal/modules/cjs/loader:1207:32)
79.89 npm ERR!     at Module._load (node:internal/modules/cjs/loader:1023:12)
79.89 npm ERR!     at cjsLoader (node:internal/modules/esm/translators:356:17)
79.89 npm ERR!     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
79.89 npm ERR!     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
79.90 npm ERR!     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
79.90 npm ERR!     at async loadESM (node:internal/process/esm_loader:28:7)
79.90 npm ERR!
79.90 npm ERR! Node.js v20.11.1
79.91
79.91 npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-03-20T22_59_02_875Z-debug-0.log
------
failed to solve: process "/bin/sh -c npm install && npm run build" did not complete successfully:
exit code: 1

**Comment by pecbeck** [comment]
Giving up for tonight. Quite a learning curve this docker stuff,

Thanks for patience

**Comment by IRHM** [comment]
Of course @pecbeck, let me know if i can help with anything else if you give it another shot, here or on Matrix.

I think there's definitely something somewhere causing it to get your architecture wrong.

The npm log is confusing, looks like it says you are on linux and using arm, then lists linux-arm as a supported arch, but doesn't use it for some reason?

**Comment by pecbeck** [comment]
Installed docker (twice) using script from docker.com, as it occurred to me yesterday I might be using 32bit. No idea how to force 64bit, script should surely sort that out. Bizzare

**Comment by IRHM** [comment]
> Installed docker (twice) using script from docker.com, as it occurred to me yesterday I might be using 32bit. No idea how to force 64bit, script should surely sort that out. Bizzare

Yup that is definitely very weird. I had a look at their site, if you are following steps for raspberry pi os, it might force to 32 bit (the table says only 32 bit arm is supported for that os).

I have debian on my pi, if I remember correctly, I followed these steps (install using apt repository): https://docs.docker.com/engine/install/debian/#install-using-the-repository

Maybe when you give it another shot, you could try uninstalling and following that guide (if you havent already).

**Comment by pecbeck** [comment]
Removed and installed docker using install I  your email. Tried build , failed againRan compose, exit 0 againDocker versioncker versionClient: Docker Engine - Community Version:           26.0.0 API version:       1.45 Go version:        go1.21.8 Git commit:        2ae903e Built:             Wed Mar 20 15:18:40 2024 OS/Arch:           linux/arm Context:           defaultServer: Docker Engine - Community Engine:  Version:          26.0.0  API version:      1.45 (minimum version 1.24)  Go version:       go1.21.8  Git commit:       8b79278  Built:            Wed Mar 20 15:18:40 2024  OS/Arch:          linux/arm  Experimental:     false containerd:  Version:          1.6.28  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb runc:  Version:          1.1.12  GitCommit:        v1.1.12-0-g51d5e94 docker-init:  Version:          0.19.0  GitCommit:        de40ad0Running compose without platform in yaml givesWARN[0000] Using /home/pi/watcharr/compose.yamlWARN[0000] /home/pi/watcharr/compose.yaml: `version` is obsolete [+] Running 0/1 ⠇ watcharr Pulling                                                                          0.7s no matching manifest for linux/arm/v8 in the manifest list entriesBoy, am I tired and confused now...CheersSent from my Galaxy
-------- Original message --------From: Mr ***@***.***> Date: 20/03/2024  23:31  (GMT+00:00) To: sbondCo/Watcharr ***@***.***> Cc: pecbeck ***@***.***>, Mention ***@***.***> Subject: Re: [sbondCo/Watcharr] No manifest for raspberry pi4 (Issue #422) 

Installed docker (twice) using script from docker.com, as it occurred to me yesterday I might be using 32bit. No idea how to force 64bit, script should surely sort that out. Bizzare

Yup that is definitely very weird. I had a look at their site, if you are following steps for raspberry pi os, it might force to 32 bit (the table says only 32 bit arm is supported for that os).
I have debian on my pi, if I remember correctly, I followed these steps (install using apt repository): https://docs.docker.com/engine/install/debian/#install-using-the-repository
Maybe when you give it another shot, you could try uninstalling and following that guide (if you havent already).

**Comment by IRHM** [comment]
@pecbeck found another post online, does running this command return 32 or 64?

`getconf LONG_BIT`

Hopefully 64, but if not, may need to reinstall your os

https://raspberrypi.stackexchange.com/a/144761

**Comment by pecbeck** [comment]
Genius! That's the problem is says 32 bit even though Arch indicates 64! What a shambles is raspian.I installed os years ago  would never deliberately used 32 bit, so no idea what happened I'll go through pain of new os and all my other apps, ensuring its 64 bitReally appreciate your diligencePaulSent from my Galaxy
-------- Original message --------From: Mr ***@***.***> Date: 21/03/2024  01:01  (GMT+00:00) To: sbondCo/Watcharr ***@***.***> Cc: pecbeck ***@***.***>, Mention ***@***.***> Subject: Re: [sbondCo/Watcharr] No manifest for raspberry pi4 (Issue #422) 
@pecbeck found another post online, does running this command return 32 or 64?
getconf LONG_BIT
Hopefully 64, but if not, may need to reinstall your os
https://raspberrypi.stackexchange.com/a/144761

**Comment by IRHM** [comment]
Glad we pinpointed the problem @pecbeck, let me know how it goes after a reinstall.

It might not have been your fault if you installed it years ago, I think they only released a 64 bit pi os version recently (if i'm remembering correctly)

**Comment by pecbeck** [comment]
It's working! Many thanks, great learning curve. You only really learn something when things go wrong Hope this helps others newcto docker (and confusion of raspberry bits)PaulSent from my Galaxy
-------- Original message --------From: Mr ***@***.***> Date: 21/03/2024  14:07  (GMT+00:00) To: sbondCo/Watcharr ***@***.***> Cc: pecbeck ***@***.***>, Mention ***@***.***> Subject: Re: [sbondCo/Watcharr] No manifest for raspberry pi4 (Issue #422) 
Glad we pinpointed the problem @pecbeck, let me know how it goes after a reinstall.
It might not have been your fault if you installed it years ago, I think they only released a 64 bit pi os version recently (if i'm remembering correctly)

**Comment by IRHM** [comment]
That's great to hear @pecbeck! Glad it's working!

Those are some wise words you speak.

I'll close this issue now, but if you have any other problems, please feel free to open another one.

Thanks for creating the issue and for your interest in Watcharr!

**Comment by pecbeck** [comment]
Thanks, where do I log other problems  [yes already!lSent from my Galaxy
-------- Original message --------From: Mr ***@***.***> Date: 21/03/2024  16:04  (GMT+00:00) To: sbondCo/Watcharr ***@***.***> Cc: pecbeck ***@***.***>, Mention ***@***.***> Subject: Re: [sbondCo/Watcharr] No manifest for raspberry pi4 (Issue #422) 
That's great to hear @pecbeck! Glad it's working!
Those are some wise words you speak.
I'll close this issue now, but if you have any other problems, please feel free to open another one.
Thanks for creating the issue and for your interest in Watcharr!

**Comment by IRHM** [comment]
No problem @pecbeck, you can create a new issue here: https://github.com/sbondCo/Watcharr/issues/new/choose
