### ISSUE TITLE
Ability to remove from list inside content pages

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#424]
I have wrongly added a movie with a similar name and rated it. Now, there is currently no way to remove the entry.

Ideally there should be a way to remove an entry altogether from the tiles. Please consider adding such a feature.

**Comment by n00b12345** [comment]
This is already available. Since I was using Watcharr on a phone, the delete option was not clearly visible. Sorry about that.

**Comment by IRHM** [comment]
Hey @n00b12345, thanks for opening an issue, we probably should improve this.

Having the delete option only available via the poster on your watchlist might confuse everyone.

I think we should probably add a button near the statuses on the main page for the show/movie?

**Comment by n00b12345** [comment]
I think that's a very good idea and will probably be helpful for people using Watcharr on a touchscreen device.
