### ISSUE TITLE
Allow Requesting (Sonarr/Radarr) via Jellyfin account

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [sbondCo/Watcharr#425]
Hi,

Is it possible to have the sonarr & radarr integration within the Jellyfin account as well?

**Comment by IRHM** [comment]
Hey @Gandalf-the-Blue, currently the only way would be to give your jellyfin account admin.

I'm just realising I haven't documented this on the site, but I have written a bit in this release: https://github.com/sbondCo/Watcharr/releases/tag/v1.19.0 in the "Getting admin on an existing account' section.

Will update docs with that soon.

ps: the integration is only about 50% complete, i should probably complete that at some point.

**Comment by Gandalf-the-Blue** [comment]
That worked, thanks!
I hope this process becomes a bit smoother and via UI once the integrations are complete, and user management is also done :)

**Comment by IRHM** [comment]
Created a guide on the docs site for restoring admin: https://watcharr.app/docs/server_config/restoring-admin

Just merged #437 which allows giving users a `request content` permission, which enables requesting for Sonarr/Radarr. There's no approving requests though, anyone with that permission can add shows/movies at will. Hopefully will be released soon.

Going to close this issue now, feel free to open another if anything else comes up and thanks for opening this one!
