### ISSUE TITLE
Import doesn't recognize previous export file

### ISSUE THREAD

**Issue by simonbcn** [sbondCo/Watcharr#436]
```
Arch Linux
Docker 25.0.4
Watcharr 1.36.0
```

I forgot what my admin account was so I exported (_from the `Profile` option_) the data. I deleted the files (`watcharr.*`) inside the `data` folder and restarted docker.
I created a new administrator account and tried to import the previously exported file (`watcharr-export.json`) but it does not recognize it: 
![image](https://github.com/sbondCo/Watcharr/assets/428231/30feaef4-0555-40fc-b6a6-d488411e8552)

On the other hand, the log file shows absolutely nothing about this error.

**Comment by IRHM** [comment]
Hey, sorry about that @simonbcn. Currently importing a watcharr export is not possible.

There is a PR (#389) that I'm planning to merge for the next release that should add this functionality.

Sorry again, hopefully I can get the next version out in the next day or so.

Related #130

**Comment by simonbcn** [comment]
Anyway, regardless there is an option to export the watcharr data to a csv or txt file. When it comes to importing data from one user to another, I think it would be better to be able to do it directly instead of having to do the intermediate step of exporting to a file and then importing it again. It would also be faster considering it is a transfer of data from one user to another within the same database.

**Comment by IRHM** [comment]
> Anyway, regardless there is an option to export the watcharr data to a csv or txt file. When it comes to importing data from one user to another, I think it would be better to be able to do it directly instead of having to do the intermediate step of exporting to a file and then importing it again. It would also be faster considering it is a transfer of data from one user to another within the same database.

You're right, that would be much better, though I'm not sure if it's worth the time investment to develop (not sure if anyone would use it).

Feel free to make a new issue suggesting this though, if I find time or anyone else does, we could add it in. Would also help to see if anyone else needs this.

Thanks!
