### ISSUE TITLE
Unable to connect to Plex host

### ISSUE THREAD

**Issue by simonbcn** [sbondCo/Watcharr#441]
```
Arch Linux
Watcharr 1.36.0
Plex Server 1.40.1.8227
```

I have followed the instructions [on the help page](https://watcharr.app/docs/server_config/plex-auth) but it does not connect:
```
❯ cat watcharr.log
...
[GIN] 2024/03/26 - 13:51:16 | 204 |   15.565006ms |     192.168.1.3 | POST     "/api/auth/admin_token"
[GIN] 2024/03/26 - 13:51:20 | 200 |    3.162625ms |     192.168.1.3 | GET      "/api/server/config"
[GIN] 2024/03/26 - 13:51:20 | 200 |    7.047933ms |     192.168.1.3 | GET      "/api/server/stats"
time=2024-03-26T13:51:37.503Z level=ERROR msg="updateConfigPlexHost: Failed to get plex server identity!" error="Get \"http://localhost:32400/identity\": dial tcp 127.0.0.1:32400: connect: connection refused"
[GIN] 2024/03/26 - 13:51:37 | 403 |    9.851046ms |     192.168.1.3 | POST     "/api/server/config/plex_host"
[GIN] 2024/03/26 - 13:51:41 | 403 |    1.098005ms |     192.168.1.3 | POST     "/api/server/config" 
```

**Comment by IRHM** [comment]
Hi @simonbcn, how is your plex server setup/exposed?

Looks like maybe it is unaccessible from inside Watcharrs container (assuming you are using it with docker).

Does the url `http://localhost:32400/identity` load in your browser?

**Comment by simonbcn** [comment]
Yes, sorry, I forgot to mention that I run `watcharr` using `docker`.

That URL is accessible in browser.

**Comment by IRHM** [comment]
> Yes, sorry, I forgot to mention that I run `watcharr` using `docker`.
> 
> That URL is accessible in browser.

No problem, do you think you could try going into the container to try loading that url from there?

I think `docker exec -it <container id> /bin/sh` will get you in, then hopefully `wget <url>` works (hopefully wget is available, might need to try something else or install it if not).

If that works or not should help us figure out what the problem could be.

**Comment by simonbcn** [comment]
It cannot connect from inside the container:
```
❯ docker exec -it 1baf2145b754 /bin/sh
/ $ wget http://localhost:32400/identity
Connecting to localhost:32400 (127.0.0.1:32400)
wget: can't connect to remote host (127.0.0.1): Connection refused
```
How can I allow that container to access _localhost_?

**Comment by IRHM** [comment]
Hm that's a tricky one @simonbcn, I'm not too sure.

How is your Plex server setup? Is it also setup is a docker container, with it's port fully exposed?

You could try setting `network_mode` to `host` in your watcharr compose file, that might be an easy fix, but doesn't fix the root problem I don't think.

----

I just realised, you might need to use your local ip (eg 192.168.x.x or similar that points to your computer on your network) instead of localhost.

**Comment by simonbcn** [comment]
Hi, yes, using the local IP works.
How it works the integration with Plex? When I see something in Plex, it's updated in Watcharr automatically?

**Comment by IRHM** [comment]
> Hi, yes, using the local IP works. How it works the integration with Plex? When I see something in Plex, it's updated in Watcharr automatically?

Currently after plex is setup, you'd have to then login via plex, then you can do a manual sync.

No automations have been setup at the moment.

**Comment by simonbcn** [comment]
This part is not documented and is quite confusing. 
What is the user to use in Plex, the same as in Watcharr, with the same password?
Where do I have to do the manual sync?

**Comment by IRHM** [comment]
@simonbcn If you logout, then you should see a 'continue with Plex' button. Unfortunately at the moment there's no way to link a Watcharr account with a Plex one.

You can do a manual sync in your profile page, at the bottom you should see a 'Sync with Plex' button.

**Comment by simonbcn** [comment]
ok, I have already been able to do it. Is there any way to transfer data from one watcharr account to another? Since I now have 2 accounts: the initial one with all my data (_1712 movies and 467 TV series_) and the Plex one.

**Comment by IRHM** [comment]
> ok, I have already been able to do it. Is there any way to transfer data from one watcharr account to another? Since I now have 2 accounts: the initial one with all my data (_1712 movies and 467 TV series_) and the Plex one.

Not at the moment. The next version will let you do this (import a watcharr export), it should be released today or tomorrow.
