### ISSUE TITLE
Mark viewed/rated in search results

### ISSUE THREAD

**Issue by simonbcn** [sbondCo/Watcharr#448]
It would be useful when I do a search to be able to see at a glance what movies/series from that list I have watched/rated. 
Especially if I have checked some option in `Detailed view` > `Shown details`.

For example, I have the movie "_Cherry Falls_" marked as watched:
![Captura desde 2024-03-28 23-12-46](https://github.com/sbondCo/Watcharr/assets/428231/eb465a96-8a2e-4077-b30f-5d5a1a8b8c61)

But when I do a search for this movie, there is nothing to tell me at a glance whether I have already seen it or not. I have to mouse over it to see it:
![Captura desde 2024-03-28 23-12-28](https://github.com/sbondCo/Watcharr/assets/428231/26b3f289-ade6-4980-a251-4285c39fd56a)

![image](https://github.com/sbondCo/Watcharr/assets/428231/d4b439f4-25bb-4506-a494-280c6631c3bf)

**Comment by IRHM** [comment]
Hi @simonbcn, we should definitely improve on this, thanks for opening the issue. I'll get to it when possible.

The extra details probably should work app wide, as you mention.
