### ISSUE TITLE
[Request] Docker Hub

### ISSUE THREAD

**Issue by LoganJFisher** [sbondCo/Watcharr#451]
Could this repository be copied to Docker Hub? That would allow the image to easily be accessed using the Synology Container Manager.

**Comment by IRHM** [comment]
Hey @LoganJFisher, thanks for opening this issue, it's unfortunate that it's hard to use ghcr with that system, I will look into also publishing to the docker hub.

**Comment by IRHM** [comment]
@LoganJFisher Just published a `dev` image to Docker Hub: https://hub.docker.com/r/sbondco/watcharr

There's only a few dependency updates that make the image differ from the latest production image release, so it should be safe to use for now until I can get a proper release out.

Let me know if you have any troubles!

**Comment by LoganJFisher** [comment]
Seems to work perfectly! Thank you for this! You were super fast to do this, which was just awesome of you. 😁

**Comment by IRHM** [comment]
Great to hear @LoganJFisher, no problem! Hope you enjoy the app!

I'll close this issue for now, please re-open or create a new issue if you run into any other problems.
