### ISSUE TITLE
[Feature Request] Sort by last activity

### ISSUE THREAD

**Issue by gardebreak** [sbondCo/Watcharr#455]
I'm looking for a way to sort my "Finished" movies based on the last date I watched them, i.e. the date they were last marked as "Finished."

Side note: the icons for "Sort" and "Filter" in the UI seem to be swapped. The funnel icon is traditionally used for Filter, and the three stacked lines are used for Sort, but in the Watcharr UI they are reversed.

Thanks for your work developing Watcharr!

**Comment by IRHM** [comment]
Hey @gardebreak, thanks for opening this issue! That must be why I get confused everytime I try to filter/sort.

Currently this is half possible if you filter for only movies, then sort by `last changed`, but of course it'll be incorrect if you change it for anything other than marking as finished at a later date.

Will get to this when possible!
