### ISSUE TITLE
A better way to view reviews

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#464]
Right now, the default view for reviews is that of a text editor. While that works well for new movies/shows when writing new reviews, for content that has already been reviewed, reading is not particularly enjoyable. For lengthy reviews, scrolling is not very easy.

I like to write lengthy reviews of movies and shows. I also like to revisit my reviews (read and update them). So, a different approach (larger viewing area or a separate viewer with an "edit" button once a review has been added) would be nice to have.

I understand that this may not be possible right now. I'm only asking for this to be considered as a feature at some point during development.

**Comment by IRHM** [comment]
Hey @n00b12345, thanks for your input on the review/thoughts feature and sorry it's been a pain to use.

I admit it is pretty barebones at the moment, we will definitely improve on this.

I like your idea, if a review has already been written, we can show a snippet of it and allow it to be opened in a modal/popup along with an edit button to turn it back into a text editor when needed.

Thanks!
