### ISSUE TITLE
Search Filters

### ISSUE THREAD

**Issue by cerxil** [sbondCo/Watcharr#472]
Currently for me there is no reason to have the game API there since you can't filter your search

**Comment by IRHM** [comment]
Hi @mommyune, thanks for opening this issue.

We can definitely look at adding filters to search, I can see how that would improve the search experience quite a lot.

I've created a new issue to track deleting users: [#473](https://github.com/sbondCo/Watcharr/issues/473)

**Comment by cerxil** [comment]
Fixed my deleted user issue by generating a long password atm
