### ISSUE TITLE
Imported activity all have the same timestamp

### ISSUE THREAD

**Issue by druckdev** [sbondCo/Watcharr#480]
When importing a previously exported Watcharr JSON, the timestamps of different activity events are all set to the most recent one. This also reverses their order making the most recent event appear at the bottom.

**Comment by IRHM** [comment]
Hi @druckdev, sorry this is causing you issues.

Do the dates and times look right in the exported json file?

I will have a look into this when possible, hopefully tonight.

**Comment by druckdev** [comment]
Yes, they do.

I also did some light debugging through prints and it looked as if up into `addActivity` the timestamps are correct. Almost as if they are being overwritten later.

I am not very proficient with Go but could it be caused by some kind of pass-by-reference issue? I saw that `CustomDate` is defined as a pointer in the `Activity` and `ActivityAddRequest` structs.

Thanks!

**Comment by IRHM** [comment]
I haven't touched the code in a while, but yep, you might be right on that. Will definitely check this out.

By any chance, if you're able to provide your watcharr json export (not all of it's needed, just one movie/show that is broken), it may help me reproduce later, incase I can't tonight (incase you go offline, I'll have it as a backup so this issue won't be delayed an extra day if i need it).

Thanks for looking into it too, it'll help me pin point the issue quicker!

**Comment by druckdev** [comment]
Oh, I just reopened my library and noticed that the timestamps are correct now... After further testing it seems like the movies have the wrong timestamps directly after the import but the correct ones after a page refresh. Navigating to a different movie and back does not help though - I needed to actually refresh the page.

Here an example json:

```
[
  {
    "id": 1,
    "createdAt": "2024-04-15T12:50:30.403313124+02:00",
    "updatedAt": "2024-04-15T12:50:43.247365724+02:00",
    "deletedAt": null,
    "status": "WATCHING",
    "rating": 8,
    "thoughts": "",
    "content": {
      "id": 1,
      "tmdbId": 226979,
      "title": "Test",
      "poster_path": "/tTWRomgIMOoIB3CJLPlVbqSawEm.jpg",
      "overview": "San Francisco, 1985. Two opposites attract at a modern dance company. Together, their courage and resilience are tested as they navigate a world full of risks and promise, against the backdrop of a disease no one seems to know anything about.",
      "type": "movie",
      "release_date": "2013-06-29T00:00:00Z",
      "popularity": 6.698,
      "vote_average": 6.8,
      "vote_count": 197,
      "imdb_id": "tt2407380",
      "status": "Released",
      "budget": 0,
      "revenue": 0,
      "runtime": 89,
      "numberOfEpisodes": 0,
      "numberOfSeasons": 0
    },
    "activity": [
      {
        "id": 1,
        "createdAt": "2024-04-15T12:50:30.408406997+02:00",
        "updatedAt": "2024-04-15T12:50:30.408406997+02:00",
        "deletedAt": null,
        "watchedId": 1,
        "type": "ADDED_WATCHED",
        "data": "{\"rating\":3,\"status\":\"FINISHED\"}"
      },
      {
        "id": 2,
        "createdAt": "2024-04-15T12:50:34.562653432+02:00",
        "updatedAt": "2024-04-15T12:50:34.562653432+02:00",
        "deletedAt": null,
        "watchedId": 1,
        "type": "RATING_CHANGED",
        "data": "8"
      },
      {
        "id": 3,
        "createdAt": "2024-04-15T12:50:43.252948636+02:00",
        "updatedAt": "2024-04-15T12:50:43.252948636+02:00",
        "deletedAt": null,
        "watchedId": 1,
        "type": "STATUS_CHANGED",
        "data": "WATCHING"
      }
    ]
  }
]
```

**Comment by IRHM** [comment]
@druckdev Thanks again for reporting this, happy to see it looks like it hasn't affected your list after that refresh.

You were right, it was an issue with it using the same pointer for all of the dates, so when returned, the object would have the same value for all of the dates (but each activity is added sequentially so it didn't effect the values in the database).
