### ISSUE TITLE
Sort by added date

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#488]
Since there are lots of movies that I have watched before I started using Watcharr (thank you for making dates editable), it would make sense to have an option to sort movies/shows based on the edited added date.

That way, the movie or show I am currently watching stays on top and the ones I have already marked as watched on an older date (say October 2020) stays lower down in the page.

**Comment by IRHM** [comment]
Hey @n00b12345, sorry this took a while for me to comment on.

Just to confirm, this would be the possibility to sort by the oldest activities date or is this the same as https://github.com/sbondCo/Watcharr/issues/455 [#479] (if so, i've just seen that i have to fix it #493, but if it's the same functionality you were looking for, let me know)?

**Comment by n00b12345** [comment]
@IRHM it's exactly the same as #493


Thank you so much for working on this.

**Comment by IRHM** [comment]
Great @n00b12345, thanks for confirming! I'll close this issue now, just going to look into fixing that issue now!
