### ISSUE TITLE
Ability to pin or mark a show/movie as sticky

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#489]
The ability to pin a movie or show would be nice to have.

This helps in case I am:

1. Watching a show where there are multiple episodes and seasons, making it easy to rate every episode as I watch it, without having to search for it
2. Watching a movie or a show again as a repeat-watch and will therefore have to edit the review

**Comment by IRHM** [comment]
Hey @n00b12345, cool idea!

Would you expect pinned items to always be at the top of the list, no matter the sort/filters applied (or do you think applying filters/sorts should hide them?). Maybe we could add a button under the filter menu for toggling pinning of items too?

If you have any ideas of where we could put a pin button, I'm happy to hear them! I was thinking inside the movie/show page, next to the new delete button?

**Comment by n00b12345** [comment]
@IRHM I think inside the movie/show page is perfect. Because putting it anywhere else on the main page would clutter the UI.
