### ISSUE TITLE
Sort by Last Finished doesn't take custom dates into account

### ISSUE THREAD

**Issue by gardebreak** [sbondCo/Watcharr#493]
Hey,

Thanks for adding the ability to sort by Last Finished. It doesn't seem to be taking custom "Finished" dates into account yet. I have a bunch of movies that I have added and backdated to the actual date that I watched them, by clicking on the activity log to bring up the "Edit Activity" dialogue and setting the actual watched date there. Finished dates set like this do not sort properly when sorting by "Last Finished."

**Comment by IRHM** [comment]
Hey @gardebreak, thanks for reporting this, I just had a look and I only made it look at the `updatedAt` date on the activity, which doesn't help! Will fix this (by using the custom date you've set, and falling back to updatedAt if it isn't set).
