### ISSUE TITLE
Feature Request: Emby Support (branding)

### ISSUE THREAD

**Issue by rguinn829** [sbondCo/Watcharr#500]
Please add Emby support and sync with emby

**Comment by IRHM** [comment]
Hey @rguinn829, congratulation for opening the 500th ticket! You have won, nothing ;(

Anywayz, have you tried logging in with the jellyfin button but setting up jellyfin host on the server to point to your emby install?

Edit: not sure if we need *should* differenciate emby/jellyfin users if it works incase they both differ in some crazy way in the future.

**Comment by rguinn829** [comment]
Wohoo I won! 

No i did not think of that let me give it a go

**Comment by rguinn829** [comment]
ok now i am stupid that worked and its syncing my content now just wish i could pick the button to say emby for my family

**Comment by IRHM** [comment]
@rguinn829 Glad it's working!

I'll leave this issue open, maybe we should add a checkbox `Using Emby` that can change the jellyfin text/logos to embys text/logos.

**Comment by rguinn829** [comment]
Thank you that would be amazing
