### ISSUE TITLE
Login for Demo?

### ISSUE THREAD

**Issue by lukyjay** [sbondCo/Watcharr#511]
Hi

I am trying to try your software using the demo https://beta.watcharr.app/ but it prompts for a login. I've searched but can't find the login anywhere. Am I missing something?

Thank you

**Comment by IRHM** [comment]
Hey @lukyjay, thanks for making this issue!

There is no demo login, you can just register with any random username/password.

Thanks for trying out Watcharr!

**Comment by IRHM** [comment]
Oh, incase you missed it, there's a link under the login button "Not A User?", if you click that, it'll let you register an account.

Sorry if that's what confused you, i guess it is kind of cryptic.

**Comment by lukyjay** [comment]
Oh, I see. Thank you 😊
