### ISSUE TITLE
Easier UI and quicker mark season done

### ISSUE THREAD

**Issue by cerxil** [sbondCo/Watcharr#532]
There just ideas.

Currently there is no quick way to see what season you are other then looking at the activity,
or going back and then -> Show details -> Watching season -> scroll back to item
Would be nice if you reused the pin option as the marked season your watching

Currently there is a season status tho when you put it on Finished the database still reads it as current season
Instead should push all episodes to finished (Nice for cartoons with double episodes)

Love the project further and curious where it will go.

**Comment by IRHM** [comment]
Hi @mommyune, thanks for making this issue and for your ideas!

I think we could probably use the watch statuses for episodes to default select a season on the season/episode list when you're in a shows page. Do you think that would work for you?

I believe #380 should improve on your second point.

Thanks again!

**Comment by IRHM** [comment]
Going to close this issue now. I believe #602 has resolved the first half of this issue (preload last clicked on season), and we can track the second part of this issue (marking whole season finished) in #380.

Thanks for making this issue, please feel free to reopen or create a new issue if I'm missing something.

Edit: Oh and the 'Extra Details' view should help with part 1, by showing the latest watching season on the poster in your watched list.
