### ISSUE TITLE
[Feature] Import from Ryot

### ISSUE THREAD

**Issue by oPisiti** [sbondCo/Watcharr#556]
Hi :v:

I've been testing watcharr lately and it seems to be great!
However, I'm trying to migrate from [Ryot](https://github.com/IgnisDa/ryot) and the current import methods don't support that.
I have a bit of experience with JS and am fairly confident I can implement this new import option.
As far as I understand, this would be done by adding a new else if entry inside the "getList()" function in "/src/routes/(app)/import/process/+page.svelte"

Is this something you guys are interested in?
If so, any tips would be much appreciated :+1:

**Comment by IRHM** [comment]
Hey @oPisiti, thank you for your interest in Watcharr and for building out this feature!

The client side import works like this:
1. `import/+page.svelte` will handle reading the selected import file and changing it to conform to the `ImportedList[]` type. It then stores the data and redirects to the processing page. (I'm not sure what ryot exports look like, but you can likely copy an existing function in there and repupose it).
2. `import/process/+page.svelte` takes the data, displays it and will do the importing. If the data was formed correctly is step 1, it should be as simple as copying the "watcharr" if else statement and changing it to ryot (I forget exactly why some of the cases in that file are also changing around the data, hopefully it is that simple).

Hopefully that can help you get started, feel free to reach out if you have any other questions. Thanks again!

**Comment by oPisiti** [comment]
Hi, again!

Thank you for the tips. 
I was able to create the import process and it seems to be working pretty well.
I have about 860 movies and 8 k episodes and it took 40 min, which I imagine is expected.

However, I encountered some discrepancies while reviewing the summaries for the media after the import.
Under "Profile",  it says I have **848** movies and **80** shows, while in "Server Settings", **861** movies and **175** shows. 
The summary under "Server Settings" shows basically the correct values (Ryot kind of messes the count, so it is hard to say for sure).
There is only one user on the server. Is this behavior a known bug or do I need to check something on the code I have changed?

And another question: is it ok for me to change the default icon on the import button I created to that of Ryot? Like it was done with Movary. Legally speaking.

**Comment by IRHM** [comment]
Hey @oPisiti, that is great to hear!

There's a 1 or 2 second hardcoded gap we leave between inporting each item, so 40 mins might be about right for that much content. (Might look into changing that in the future, 40 mins does seem long)

The profile page only counts movies/shows with a status of FINISHED and the server stats page counts any movie/show with any status (might be why the stats are different). That looks like a lot of shows without the FINISHED status, maybe a bug there or maybe you DROP/PLANNED a lot of them?

I'm not sure about the lagalities of using ryots logo, I didn't think about that; maybe we use it and just take it down if are asked to do so? Using a logo to reference an app seems like an ok use to me, not 100% sure, I think it should be alright.

**Comment by oPisiti** [comment]
Thank you for that insight, there are a lot of PLANNED or DROPPED series :relieved:
