### ISSUE TITLE
[Enhancement] Better units

### ISSUE THREAD

**Issue by oPisiti** [sbondCo/Watcharr#565]
Hi :v:,

I'd like to propose some changes regarding the time units used.

1. Abbreviation of minutes as "min" both in series and episodes summaries:

      ![image](https://github.com/sbondCo/Watcharr/assets/78967454/57994c8e-99ca-4254-ad61-78200cb2ea17)  => ![image](https://github.com/sbondCo/Watcharr/assets/78967454/4df0bda6-8353-4f53-b470-c2f232b3c010)

      ![image](https://github.com/sbondCo/Watcharr/assets/78967454/3bef20f8-34e8-4b54-96e8-dc90778cdaf9) => ![image](https://github.com/sbondCo/Watcharr/assets/78967454/e6ef5894-7851-4162-92dd-b6761e2924cb)

2. In profile/settings, change the total count to months/weeks/day/hours instead of hours/min:

      ![image](https://github.com/sbondCo/Watcharr/assets/78967454/7165d85f-091d-498b-ad33-8feff1faab93) => ![image](https://github.com/sbondCo/Watcharr/assets/78967454/3bbc3824-d33c-4b1d-906b-02e67f88edcc)

If these ideas are in line with the project's vision , I make myself available to implement them

**Comment by IRHM** [comment]
Hey @oPisiti, thanks for the suggestions, I think they make a lot of sense. Feel free to make a PR making those changes, that would be great!
