### ISSUE TITLE
All watch history wiped

### ISSUE THREAD

**Issue by LoganJFisher** [sbondCo/Watcharr#589]
I recently updated my Watcharr version, and I just found that all of my watch history is gone. Absolutely no record of it anywhere.

There doesn't seem to be anything that can be done to fix this since I foolishly hadn't exported and backed up at any point, but I thought I should say something about it.

Moving forward, would you consider introducing an automatic backup system? Maybe automatically exporting to Google Drive or something?

**Comment by LoganJFisher** [comment]
I apologize if my tone comes off as at all angry. I'm clearly annoyed at having lost all this data and now having to rebuild it from memory, but the lack of a backup is entirely my own fault.

**Comment by IRHM** [comment]
Hi @LoganJFisher, sorry to hear your data got wiped.

How did this happen? Did your docker volume containing the database get deleted when your container was shutdown or is this something Watcharr did to your data?

Unfortunately Watcharr doesnt have any sort of auto backup feature, just a guide on how to backup your server: https://watcharr.app/docs/server_config/backup

The guide is mostly meant for helping recognize which files need to be backed, so they can be, however you handle backups on your server.

Not sure that I'd want to code auto backups to a cloud service, maybe we could create auto backup zips somewhere (but that might just be redundant). Ideally the backup would be setup by the user, then they have complete control over how its packaged and where its backed up to (eg by using duplicati, borg or a simple shell script ran daily, etc).

p.s. hopefully your list wasn't massive and won't take too long to rebuild manually. Maybe this was a reminder from the universe to setup a backup script or app (i put off doing it for way too long and after I did, it saved me quite a few times).

**Comment by LoganJFisher** [comment]
I honestly have no clue. I updated I think 2 days ago, and I woke up today and found my list empty with no sign of the data anywhere to my found.

I had a few hundred shows and movies on there. I probably won't remember all of the finished things I had on there, but it's the in-progres stuff that's a bigger concern anyway.

As for backups, I get where you're coming from with not wanting to build in any sort of dependence on an external service. Is there any chance you would consider some sort of built-in tool though? Even just the ability to have it periodically show a popup in Watcharr that prompts me to backup (maybe like once a month) would be useful.

**Comment by IRHM** [comment]
That sucks, hopefully doesn't happen again, to be cautious you can copy your whole data volume/folder with watcharr not running before backing up anytime in the future.

Thank you for the suggestions, I will come back to them in the future, I'll think about them a bit more.

**Comment by LoganJFisher** [comment]
It happened again. Fortunately, I had made a backup just a couple of weeks ago, so I'm only missing a few episodes of shows I've watched since then.

I think I'll make it a habit to do a manual backup before every update from now on, but I'd appreciate it if you could look into this regardless.

**Comment by IRHM** [comment]
Hi @LoganJFisher, yep probably best to do a backup before each update.

I haven't heard this from anyone else, is it possible your docker volume is not persistent between reboots of your container?

Just for the sake of testing this, you could spin up a second instance with the same config (different volume ofc, but same config), create a user and add some shows, then restart the container, if your data was wiped then your volume may not be setup correctly (you might have to run stop and start commands separately, not sure if restart command would delete non persistent/mounted volumes).

**Comment by LoganJFisher** [comment]
I did as you recommended, and after restarting the shows I added to the test were still there.

I'm sure you're right though that I just have something configured wrong. I know it's a big ask, but if you could create a guide for Synology Container Manager installation so I can find where I'm messing up, that would be a huge help.

**Comment by LoganJFisher** [comment]
I did as you recommended, and after restarting the shows I added to the test were still there.

I'm sure you're right though that I just have something configured wrong. I know it's a big ask, but if you could create a guide for Synology Container Manager installation so I can find where I'm messing up, that would be a huge help.

**Comment by IRHM** [comment]
@LoganJFisher Unfortunately I have never used Synology, so I can't help too greatly with specifics.

Do you have any other containers setup with volumes that aren't getting deleted after an update? Maybe you can spot a difference between one that works properly and the broken Watcharr one.

If it isn't too much to try this, you could setup an older instance of watcharr (1 before latest), add test data, then update it, does that still break?

**Comment by IRHM** [comment]
From searching online, it looks like you setup a container with a docker compose config? Posting that may also help

**Comment by LoganJFisher** [comment]
This is my only container with persistent storage. Everything else is services like for translation and PDF editing.

**Comment by IRHM** [comment]
Do you have your docker compose config available to paste here so I can have a look?

**Comment by IRHM** [comment]
Hey, haven't heard back in a while, going to close this issue for now, feel free to respond here or open another issue if you have any more troubles!

**Comment by LoganJFisher** [comment]
Sorry, I meant to reply to this, but got distracted. I'm not entirely certain if this is what you're asking for, but maybe it is:

[Watcharr.json](https://github.com/user-attachments/files/17604051/Watcharr.json)
