### ISSUE TITLE
Bug: Do not add the cover if there was an error in the first import.

### ISSUE THREAD

**Issue by simonbcn** [sbondCo/Watcharr#595]
```
Fedora Linux 40
Watcharr 1.41.0 on Docker
```
I added a movie at a time when my internet connection was failing. It added correctly but without a cover. When the connection was restored, _Watcharr_ still did not add the cover. I deleted the movie and tried adding it again, but it still doesn't add the cover. Attached is a screen recording:

https://github.com/user-attachments/assets/141e41b4-9066-4bf9-9b8e-159ab42f1cdd

**Comment by IRHM** [comment]
Hi @simonbcn, sorry to hear about your troubles.

This makes me think that Watcharr may have created the image file in your data folder, but wasn't able to complete it, which left you with a corrupted image that wont be replaced.

Do you have any experience with your browsers dev tools? We can try to locate the image to try removing, maybe we can fix this for you now before we can get a fix out:

1. Right click the movie in your browser
2. Click `Inspect`
3. In the new popup thing, you should be in the `Inspector` tab. Look for the `img` tag (should be one above the highlighted tag):
![image](https://github.com/user-attachments/assets/312b5287-84bf-4562-aaac-1845a21aa413)
4. The bit I have highlighted (in the screenshot) will be the file name we can look for in your containers `data` folder, if it is there, try deleting it (should be under data/img).
5. (may need to restart watcharr server) now just click back into the movie on watcharr and it should re-download the image.

**Comment by simonbcn** [comment]
It doesn't work. 
I deleted the image, deleted the movie, restarted the server, re-added the movie but it still fails.
These screenshots are after completing this process:
![Captura de pantalla 2024-08-17 a las 9 09 55](https://github.com/user-attachments/assets/334f07c4-f858-4f19-99bd-68f6d563b779)

![Captura de pantalla 2024-08-17 a las 9 10 34](https://github.com/user-attachments/assets/26591e99-392f-4128-a635-ac60d590f7d7)

**Comment by IRHM** [comment]
@simonbcn oh i see, you said you deleted the image, was the file on your system? Did it not reappear afterwards?

**Comment by IRHM** [comment]
I was just able to try this myself, I can remove that image file from my `data/img` folder then after restarting the server and clicking back into the movie, it re-downloads the file.

Very weird it doesn't do the same for you.

After you complete that process:
1. Does the image file reappear in your `data/img` folder?
2. Can you view the image file outside of watcharr (by opening the jpg directly, if possible)?
3. Are any errors logged?

**Comment by simonbcn** [comment]
It worked now. It redownloaded the cover.

**Comment by IRHM** [comment]
Slightly improved the poster downloading in #658, but I don't believe that fully resolves this issue because of request caching on the server.

Going to close this in favour of #62, which I think should help resolve any outstanding issues with this by allowing manual refresh of content.

Thanks again for reporting this!
