### ISSUE TITLE
Manage activity

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#61]
Allow user to manage their content activity manually.

Editing isn't required, but deleting and adding should be added (timestamp for activity should be modifiable)

**Comment by stephaje** [comment]
I was going to dip my toes in here.

Hovering on the date adds an underline and changes cursor type, click brings up a calendar widget to edit the timestamp
+
Hovering anywhere in a row adds a red X button at the end of the row to remove it entirely

**Comment by IRHM** [comment]
Hi @stephaje, sounds good!

I do think, it might be easier if we opened a modal when the user clicks on an activity, then the modal can have all the things required for editing and a button to delete.

I think that would work better on mobile too.

What do you think?

**Comment by stephaje** [comment]
That's a good point about mobile. It's not a platform I've had to consider with my past work. I'll give that a go over the weekend.
