### ISSUE TITLE
Bug: middle click not working properly

### ISSUE THREAD

**Issue by AlexPerathoner** [sbondCo/Watcharr#620]
In views with movies and shows I can middle click with the mouse on the text of a show and (as expected) that item gets opened in a new tab. If I click on the description text the new tab isn't opened. Also, the item is now stuck in the "bigger mode", even when I stop hovering it.

https://github.com/user-attachments/assets/4fe02675-0cea-447a-a64e-e28b62feb51c

**Comment by IRHM** [comment]
Hey @AlexPerathoner, good catch, I can look into fixing this shortly when I find some time.
