### ISSUE TITLE
rating dropdown stopped appearing

### ISSUE THREAD

**Issue by senz** [sbondCo/Watcharr#654]
Expected behavior:
When hovering star icon in TV show episode/season bottom details, a dropdown is drawn, which is containing clickable numbers to set rating for episode/season.

Observed behavior:
No dropdown appears on hover.

In browser console I see a warning:
`AddToTagButton.DNsnjGRV.js:1 showRating: Containers not defined yet.`

v1.44.0

**Comment by IRHM** [comment]
Hey @senz, sorry about this.

I am seeing the same on my phone after a quick test. I will look into this as soon as possible and get a fix out.

Thanks for reporting this!
