### ISSUE TITLE
Export watched list

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#66]
A way for a user to export their own watched list (watched and content combined from tables) as JSON (and CSV?).

Requires:
- New api endpoint for exporting list
- Export button (probably in profile page) that calls the new endpoint and saves data to a file.

**Comment by kurtmgray** [comment]
This sounds like a great issue for me to tackle. I'd love to be assigned.

**Comment by IRHM** [comment]
> This sounds like a great issue for me to tackle. I'd love to be assigned.

I can assign you for sure!

I'll put it on the `v1.15.0` milestone, not sure how long `v1.14.0` will take to release, but if you are done before then, we can certainly include it in `v1.14.0` instead.

**Comment by kurtmgray** [comment]
Made some progress on this today, implementing your requested api route approach. I'm curious to hear your thoughts on retrieving the watched list from @store. Too much work for the browser?

**Comment by IRHM** [comment]
> Made some progress on this today, implementing your requested api route approach. I'm curious to hear your thoughts on retrieving the watched list from @store. Too much work for the browser?

Good to hear!

Thats interesting you mention that, I didn't think about exporting from the data we have locally in the browser. If you do it this way we can skip the api endpoint and do it all client side.

Originally I had thought we would request the endpoint to gather all our watched content (similar to how we get it already) then give it all back and we save it to a file.

The client side only way is sounding like a much better way, since we should already have all the data we need in the store (only downside I see is we may need to get a xml package clientside instead of serverside).

**Comment by kurtmgray** [comment]
Great, I'll move forward with the client side solution. I think it's probably the way to go, as well.

**Comment by kurtmgray** [comment]
Follow up question - would you care to add any error handling in the CSV conversion, whether a log or a rendered message? Seems the most likely place for something to go wrong.

**Comment by IRHM** [comment]
> Follow up question - would you care to add any error handling in the CSV conversion, whether a log or a rendered message? Seems the most likely place for something to go wrong.

You can show a simple message with the `notify` function (can look through api.ts file for examples on usage). Something like "failed to export as xml" should be good for now.

You can also log the real error with console.error().

**Comment by kurtmgray** [comment]
Thanks - one more point of clarification. Do you want json and csv, json and xml, or all 3?

**Comment by IRHM** [comment]
> Thanks - one more point of clarification. Do you want json and csv, json and xml, or all 3?

Originally I had thought just json and csv.

With there being an embedded `content` object, I'm not so sure how the data will look in a csv or xml file (my original thoughts were someone could export as csv, then import into a spreadsheet app for xml if they wanted?).

Ultimately I will leave the decision with you, whichever options (csv, xml or both) you think are suitable you can add in.
