### ISSUE TITLE
Ryot Shows Import don't take right dates

### ISSUE THREAD

**Issue by SirMartin** [sbondCo/Watcharr#663]
**Describe the bug**
I have an export from Ryot 7.6.1 (latest version at the moment) and it works fine, but the watched dates are all set to today instead of the one in the import file.

**To Reproduce**
1. Go to 'ryot import'
2. Select the ryot export file (I attached one example)
3. The imported files have a today date as watched date.

**Expected behavior**
The shows should have the same watched date that the one in the export file.

**Screenshots**
![image](https://github.com/user-attachments/assets/6d00ed85-e934-414b-8764-625bf75c6138)
![image](https://github.com/user-attachments/assets/bc58e92c-aa43-473a-856f-8a4a1962d42c)
![image](https://github.com/user-attachments/assets/4b31f83f-8f11-4185-b3a2-8e5a3f17ed86)

**Comment by IRHM** [comment]
Hey @SirMartin, thanks for reporting this!

I have created a fix which looks like it solves this problem, going to finish testing then release a new version soon for you.

Once you are able to try it out, let me know if you have any problems.

**Comment by SirMartin** [comment]
I forgot to add the file to test it. Probably too late, but here it is.
[ryot-shows-test.json](https://github.com/user-attachments/files/17390892/ryot-shows-test.json)

**Comment by IRHM** [comment]
> I forgot to add the file to test it. Probably too late, but here it is. [ryot-shows-test.json](https://github.com/user-attachments/files/17390892/ryot-shows-test.json)

Thank you, luckily I had a test file laying around that was also broken (from a few months ago, looked the same as in your screenshot though).

Let me know if you have any problems!

**Comment by SirMartin** [comment]
Do you know approximately when a new version will be released?
