### ISSUE TITLE
Invalid API key error

### ISSUE THREAD

**Issue by genelee2050** [sbondCo/Watcharr#687]
I'm getting "Invalid API key: You must be granted a valid key" error log message since this afternoon. Is it a TMDB problem or should I request my own API key? TMDB website doesn't allow register at the moment (403 error on register page)

**Comment by IRHM** [comment]
Hi @genelee2050, thanks for reporting this issue.

Is it possible you have added an empty TMDB key by accident? You can double check, in your watcharr.json, you can remove the TMDB_KEY key/value and restart watcharr to try again.

If that's not it, have you changed anything on your server recently that could have potentially caused this?

**Comment by genelee2050** [comment]
> Hi @genelee2050, thanks for reporting this issue.
> 
> Is it possible you have added an empty TMDB key by accident? You can double check, in your watcharr.json, you can remove the TMDB_KEY key/value and restart watcharr to try again.
> 
> If that's not it, have you changed anything on your server recently that could have potentially caused this?

oh silly me. that solves it.
thanks for the speedy reply!
