### ISSUE TITLE
Time parsing issue when requesting detailed movie / tv show view

### ISSUE THREAD

**Issue by 0nlyJ2W** [sbondCo/Watcharr#710]
**Edit2:** The cause of the issue was not exactly what I guested first. I debugged the issue and created a possible fix https://github.com/sbondCo/Watcharr/pull/711

**Describe the bug**
Hi,
I am facing an issue with the detailed view of movies and tv shows. The overview of all watched movies is working fine, but when I open the detailed view of a movie I am prompted with an request error and code 400.
I dug a bit deeper to attempt fixing the bug on my own. Unfortunately I only had been able to identify the source of this bug due to the log output.
The function `cacheContentMovie()` in  `server/content.go`  parses the `realeseDate` string from the movie db response. According to the logs the parsing schema alters from the schema in the code (`2006-01-02T15:04:05Z07:00` vs `2006-01-02`). Therefore the parse steps fails.
See [here](https://github.com/sbondCo/Watcharr/blob/6c404877f5d953a499476480aae7c21829590027/server/content.go#L147)
I am pretty confused how the hardcoded schema can change - or to be precise - from where the  `T15:04:05Z07:00` slug comes from and why there is the error log of the parse step missing.
Restarting the container and other basic fixing attempts did not succeed that is why I am filing this issue.
Thanks in advanced and shoutout to this great project!

**To Reproduce**
I am not quite sure how to reproduce this behavour. I have done some minor debugging but did not succeed yet.

**Screenshots**

![image](https://github.com/user-attachments/assets/7af8571e-5a35-46e8-a0c1-6006fc2e6c3e)
Error accessing detailed movie view
```
watcharr  | time=2024-12-06T23:17:08.267Z level=DEBUG msg=tmdbAPIRequest endpoint=/movie/9428 params=map[append_to_response:videos,watch/providers,similar]
watcharr  | time=2024-12-06T23:17:08.329Z level=ERROR msg="Failed to complete movie details request!" error="parsing time \"2021-02-25 11:45:24 UTC\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \" 11:45:24 UTC\" as \"T\""
watcharr  | [GIN] 2024/12/06 - 23:17:08 | 400 |   61.714702ms |       10.0.0.20 | GET      "/api/content/movie/9428?region=DE"
```
Error accessing detailed tv show view
```
watcharr  | time=2024-12-06T23:23:58.719Z level=DEBUG msg=tmdbAPIRequest endpoint=/tv/76479 params=map[append_to_response:videos,watch/providers,similar,external_ids,keywords]
watcharr  | time=2024-12-06T23:23:58.890Z level=ERROR msg="Failed to complete tv details request!" error="parsing time \"2024-05-04 02:28:16 UTC\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \" 02:28:16 UTC\" as \"T\""
watcharr  | [GIN] 2024/12/06 - 23:23:58 | 400 |  171.187799ms |       10.0.0.20 | GET      "/api/content/tv/76479?region=DE"
```

**Platform:**
- OS: Linux, DockerCompose
- Browser (latest version): vivaldi
- Watcharr Version: v1.44.2
- Docker Image: ghcr.io/sbondco/watcharr:latest

**Edit**
It seems like the [public dev-instance](https://beta.watcharr.app/) suffers from this issue as well.

**Comment by LoganJFisher** [comment]
I second this same experience on a Synology NAS using Container Manager. Restarting the container didn't help me either. It was working fine prior to today, and I had made no changes since.

**Comment by theryecatcher** [comment]
Experiencing the same seems like something on the response changed.

**Comment by 0nlyJ2W** [comment]
I think I have located the root of this issue and created a fix:
https://github.com/sbondCo/Watcharr/pull/711

**Comment by LoganJFisher** [comment]
I didn't make any changes to my local install, but it's working fine again now.

**Comment by 0nlyJ2W** [comment]
I can confirm it's working fine now. The response of the movie db api contains its former time format again.

**Comment by dieselbabyy** [comment]
Hey, so I'm a bit confused - what did you guys do to fix this issue?  I'm having a similar issue to what was noted in #711 and #712  as you can see from the screenshots below:

![chrome_KNiy0V4q5W](https://github.com/user-attachments/assets/9616e882-31ed-46f8-812d-a5e3bd0e13ff)

Here for example, is a list of movies added to my list (I'm unable to add any more new movies to it, it's effectively broken Watcharr for me completely):

![chrome_VpglVsHh91](https://github.com/user-attachments/assets/86181234-ed8e-4165-b949-da6f5caea980)

When I go to click on one of the items, say the last one added, "Blink Twice", I get this error:

![chrome_SI3aitiDKc](https://github.com/user-attachments/assets/f650aed4-9558-4974-869f-a29a350fa612)

Here's some stuff from the console, if it's of any use:

![chrome_NaFgPSXwjk](https://github.com/user-attachments/assets/179faeae-0fc8-43be-8124-df5e6292b6ac)
![chrome_cfq7ki3TdH](https://github.com/user-attachments/assets/bc80f952-042d-4548-8bb5-cee4a01a1853)

Edited to add:

This is on a VPS running Ubuntu 24.04 using Docker

**Comment by IRHM** [comment]
Hi @dieselbabyy, I believe the fault from the original issue lied with the movie db external api that we use to fetch the movie/series data, which seemed to have been fixed on their side.

Could I ask for this info:
1. Have you tried restarting watcharr (shutdown and start watcharr server up again)?
2. What version of Watcharr are you running?
3. Would you be able to share the error from the server log? (Make sure theres no private info shared)

The beta site (https://beta.watcharr.app/) seems to be working for me at the minute so I think the external api responses should be good.
