### ISSUE TITLE
Raiders of the Lost Ark movie details not loading

### ISSUE THREAD

**Issue by n00b12345** [sbondCo/Watcharr#712]
**Describe the bug**
Search for "Raiders of the Lost Ark" (1981), the Indiana Jones movie. When you tap on it, the request fails.

**To Reproduce**

1. Go to search and search for "Raiders of the Lost Ark"
2. Click on the first result
3. See error

**Expected behavior**
The movie page should open

**Screenshots**
![Screenshot_20241208_023006_Firefox.jpg](https://github.com/user-attachments/assets/99aa0e50-cb92-4415-bad1-a99647110e68)

**Platform (please complete the following information):**

- OS: Linux
- Watcharr Version: v1.44.2

**Additional context**
Other movies work fine. This may be an API issue.

**Comment by IRHM** [comment]
Hi @n00b12345, thanks for reporting. I wasn't around when this was reported, but it seems to be working for me if I lookup that movie.

Looks to be the same as #710

Will close this now, but please re-open if it is still broken for you.

**Comment by n00b12345** [comment]
> Hi @n00b12345, thanks for reporting. I wasn't around when this was reported, but it seems to be working for me if I lookup that movie.
> 
> Looks to be the same as #710
> 
> Will close this now, but please re-open if it is still broken for you.

You're right. It's fixed now. Thank you for helping 😊
