### ISSUE TITLE
More Categories

### ISSUE THREAD

**Issue by GoldBull3t** [sbondCo/Watcharr#718]
Hello, Watcharr team! First of all, I would like to congratulate you on the excellent work you've done with the app. The current categories (planned, watching, dropped, on hold and finished) already cover most of the basic needs, but I believe there is room for some improvements that could make the app even more complete and versatile.

1 Improvement Suggestion:
 1- New Customizable Categories: It would be interesting to allow users to create their own categories, to better reflect their usage styles. Example:
Favorites: For content that the user loves and wants to save.
To test: For content that sparked curiosity, but the user is not sure whether they will watch it in full.
Friends' Recommendations: A specific category to keep track of what others have suggested.

**Comment by IRHM** [comment]
Hi @GoldBull3t, thank you for your support.

I think a good way to do that in Watcharr would be to keep those example shows/movies in the PLANNED (or FINISHED for favourites) state, and then add them into separate Tags (eg, one tag for "Favourites", one for "To test", etc).

I think tags sound like they should fill in the gap for you here. I would say they are more like the categories and the planned, watched, etc buttons are more like a current state for that content.

Thanks again, please let me know if that works for you or if it's not exactly what you wanted.

**Comment by GoldBull3t** [comment]
It really works, I never thought of it that way before. Thank you very much.
