### ISSUE TITLE
IMDB import

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#725]
### Discussed in https://github.com/sbondCo/Watcharr/discussions/720

<div type='discussions-op-text'>

<sup>Originally posted by **terrytw** December 16, 2024</sup>
Can someone please tell me how to import IMDB export? I saw in an pr that it was supported alongside TMDB import, but it doesn't work for me. I clicked the TMDB import button and tries to import my IMDB export (csv) and it just doesn't work. 

Thanks!</div>

Seems we never actually added support for imdb imports.

**Comment by IRHM** [comment]
@terrytw I haven't used imdb for creating a list/rating stuff before (hope you don't mind, but I have a question). Does imdb let you export your ratings or some type of watchlist or is it just certain lists that you can export (what should we be able to import i guess is my question)?

**Comment by christaikobo** [comment]
You can export both your watchlist and ratings.

I have a sample rating export:

[sample.csv](https://github.com/user-attachments/files/18172657/sample.csv)
I have removed the majority of items, but I think the remaining data should be enough.

Let me know if you need anything else, I'd be happy to provide it.

**Comment by Seyloria** [comment]
Had the same issue comming from imdb custom lists. I for myself did a somewhat dirty workaround. I imported all my imdb list into tmdb and from there exported the ratings and watchlist again.

The tmdb export can than be reimported into Watcharr. The only thing that bothered me is the fact that i had to manually/by hand set the watchlist items 1 by 1 as "planned"(already described here [import tmdb watchlist #575](https://github.com/sbondCo/Watcharr/issues/575)).
It would be very handy if there was some kind of selection menu above the headline to set all as planned/on hold/watching etc.
