### ISSUE TITLE
Import and Sync from Jellyfin

### ISSUE THREAD

**Issue by IRHM** [sbondCo/Watcharr#82]
Import and sync watched items from Jellyfin.

I think a separate import button and sync toggle would make sense? People could import past watched items whenever without syncing?

**Comment by Gandalf-the-Blue** [comment]
Hi,
Is there any movement on this? My watch history is vast and on Jellyfin, I'd love to sync it with Watcharr though

**Comment by IRHM** [comment]
Hi @Gandalf-the-Blue,

I haven't started on this yet, I have one other task to get done, then I'll get on this one for you.

Thanks for your comment!

**Comment by IRHM** [comment]
Manual sync with jellyfin has been released in [v1.35.0](https://github.com/sbondCo/Watcharr/releases/tag/v1.35.0).

I'll create a new issue to track automatic syncing with jellyfin via daily full syncs and possibly a webhook listener to get live syncing.

Please create a new issue if you have any problems! You can find the `sync with Jellyfin` button in your profile page at the bottom, after logging in via Jellyfin.
